# hello

enum Gender {
  MALE
  FEMALE
  PREFER_NOT_TO_SAY
}

type Address {
  city: String
  houseName: String
}

type Person {
  name: String!
  age: Int
  address: Address
  partner: Person
  workedAt: [String]
  gender: Gender!
}

type Query {
  person(id: Int): Person
}
