# hello

input PersonQueryInput {
  id: Int!
  name: String = "Heyyy"
}

interface Y {
  """
  Description 1
  """
  args(
    """
    Description 2
    """
    arg1: Int = 10
  ): Int!
}

enum Gender {
  MALE
  FEMALE
  PREFER_NOT_TO_SAY
}

type Address {
  city: String
  houseName: String
}

type Person {
  name: String!
  age: Int
  address: Address
  partner: Person
  workedAt: [String]
  gender: Gender!
}

type Query {
  person(args: PersonQueryInput): Person
  test(arg: Int = 15): Int
}
